# Generated by Django 5.1.2 on 2024-10-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acas", "0002_initial_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="saltformaliaskind",
            name="ls_type_and_kind",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="uncertaintykind",
            name="ls_type_and_kind",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="rolekind",
            name="ls_type_and_kind",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="uncertaintykind",
            name="kind_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="unitkind",
            name="kind_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="valuekind",
            name="kind_name",
            field=models.CharField(max_length=255),
        ),
    ]
