# Generated by Django 5.1.2 on 2024-10-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acas', '0003_alter_abstractbbchemstructure_version_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LsSeqAnlGrp',
        ),
        migrations.DeleteModel(
            name='LsSeqContainer',
        ),
        migrations.DeleteModel(
            name='LsSeqExpt',
        ),
        migrations.DeleteModel(
            name='LsSeqItxCntrCntr',
        ),
        migrations.DeleteModel(
            name='LsSeqItxExptExpt',
        ),
        migrations.DeleteModel(
            name='LsSeqItxLsThingLsThing',
        ),
        migrations.DeleteModel(
            name='LsSeqItxProtocolProtocol',
        ),
        migrations.DeleteModel(
            name='LsSeqItxSubjCntr',
        ),
        migrations.DeleteModel(
            name='LsSeqProtocol',
        ),
        migrations.DeleteModel(
            name='LsSeqSubject',
        ),
        migrations.DeleteModel(
            name='LsSeqTrtGrp',
        ),
    ]
